/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 portal.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Canvas } from 'react-three-fiber'
import { PerspectiveCamera } from '@react-three/drei'

export function Portal(props) {
  const { nodes, materials } = useGLTF('../models/portal.glb')
  return (
    <>
    <Canvas >
      <PerspectiveCamera makeDefault position={[0,0,2]}/>
      <group  dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI]}>
        <mesh geometry={nodes.Circle_1.geometry} material={materials.black} />
        <mesh geometry={nodes.Circle_2.geometry} material={materials['Material.001']} />
      </group>
      </group>
    </Canvas></>
    
    
  )
}

useGLTF.preload('/portal.glb')
